title: yeokyeong.yoon
author: yoon
email: yeokyeongy@gmail.com

# URL settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yeokyeong-yoon.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
# Available themes for GitHub Pages:
# - minima (current)
# - architect
# - cayman
# - dinky
# - hacker
# - leap-day
# - merlot
# - midnight
# - minimal
# - slate
# - tactile
# - time-machine
theme: minima
remote_theme: jekyll/minima@v2.5.1
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Post settings
future: true  # 미래 날짜의 포스트도 표시하도록 설정

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Default settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md 