# Firebase Configuration
firebase_api_key: "AIzaSyC4XvOHbMnPNyjR3IbU0fZkNWKExMI6dEE"
firebase_auth_domain: "yeokyeongyy.firebaseapp.com"
firebase_project_id: "yeokyeongyy"
firebase_storage_bucket: "yeokyeongyy.firebasestorage.app"
firebase_messaging_sender_id: "113030891564"
firebase_app_id: "1:113030891564:web:a08ea569a7fb93a5c46989"
firebase_measurement_id: "G-TP6F1R7FD3"

# Site settings
title: "yoon's blog"
description: "Software Engineer passionate about solving meaningful problems"
author: yoon
email: yeokyeongy@gmail.com

# URL settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yeokyeong-yoon.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
# Available themes for GitHub Pages:
# - minima (current)
# - architect
# - cayman
# - dinky
# - hacker
# - leap-day
# - merlot
# - midnight
# - minimal
# - slate
# - tactile
# - time-machine
theme: minima
remote_theme: jekyll/minima@v2.5.1
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Post settings
future: true  # 미래 날짜의 포스트도 표시하도록 설정

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Default settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - functions
  - functions_temp
  - vendor
  - .git/
  - .github/
  - .gitignore
  - README.md
  - _site
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Include specific files and directories
include:
  - _posts
  - _layouts
  - _includes
  - assets
  - images

kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
  auto_ids: true
  toc_levels: 1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false
  # 들여쓰기 관련 설정
  header_offset: 0
  line_width: 80
  indent: 2
  math_engine: mathjax

# Mermaid 설정
mermaid: false
mermaid_version: "10.2.3"  # 최신 버전으로 업데이트, 하지만 비활성화됨

# 성능 최적화 설정
# incremental: true 